/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <Application.h>
#include "message_labels.h"
#include "LJIconView.h"
#include <Bitmap.h>
#include <Picture.h>
#include <TranslationUtils.h>




LJIconView::LJIconView()
 : BView(BRect(9, 10, 42, 43), "View", B_FOLLOW_TOP | B_FOLLOW_LEFT, B_WILL_DRAW | B_NAVIGABLE)
{

	_bxl_attached = false;

	    ljicon = BTranslationUtils::GetBitmap('PNG ', 126);

}

LJIconView::~LJIconView(void)
{
	}

void
LJIconView::AttachedToWindow(void)
{

	if (!_bxl_attached){
		_bxl_attached = true;
	}
    SetViewBitmap(ljicon);

}

void
LJIconView::AllAttached(void)
{

}

