/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <Application.h>
#include "message_labels.h"
#include "LJAboutMainView.h"
#include <stdio.h>



LJAboutMainView::LJAboutMainView()
 : BView(BRect(1, 0, 312, 169), "View", B_FOLLOW_TOP_BOTTOM | B_FOLLOW_LEFT_RIGHT, B_WILL_DRAW | B_NAVIGABLE)
{

	_bxl_attached = false;

		LJIcon = new LJIconView();
	titlestring = new BStringView(BRect(52, 10, 250, 43), "TitleString", "AliveJournal", B_FOLLOW_LEFT | B_FOLLOW_TOP, B_WILL_DRAW | B_NAVIGABLE);
	font1 = new BFont(be_plain_font);
	font1->SetSize(20);
	okbutton = new BButton(BRect(261, 136, 301, 160), "OKButton", "OK", new BMessage(B_QUIT_REQUESTED), B_FOLLOW_BOTTOM | B_FOLLOW_RIGHT, B_WILL_DRAW | B_NAVIGABLE);


}

LJAboutMainView::~LJAboutMainView(void)
{
	}

void
LJAboutMainView::AttachedToWindow(void)
{

	if (!_bxl_attached){
	AddChild(LJIcon);
	titlestring->SetFont(font1);
	AddChild(titlestring);
	AddChild(okbutton);
		_bxl_attached = true;
	}

}

void
LJAboutMainView::AllAttached(void)
{

	font1->SetSize(20);
}


