/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <Application.h>
#include "message_labels.h"
#include "LJLogoView.h"
#include <Bitmap.h>
#include <Picture.h>
#include <TranslationUtils.h>
#include <stdio.h>


LJLogoView::LJLogoView()
 : BView(BRect(8, 26, 188, 211), "View", B_FOLLOW_TOP_BOTTOM | B_FOLLOW_LEFT_RIGHT, B_WILL_DRAW | B_FRAME_EVENTS | B_NAVIGABLE)
{

	_bxl_attached = false;

		SetDrawingMode(B_OP_OVER);
	ljlogo = BTranslationUtils::GetBitmap('PNG ', 125);

}

LJLogoView::~LJLogoView(void)
{
//	delete ljlogo;
}

void
LJLogoView::AttachedToWindow(void)
{

	if (!_bxl_attached){
		_bxl_attached = true;
	}
	SetDrawingMode(B_OP_OVER);

	SetViewBitmap(ljlogo, B_FOLLOW_ALL, 0);
}

void
LJLogoView::AllAttached(void)
{

}

void
LJLogoView::FrameResized(float width, float height)
{

Invalidate(Bounds());
}


