/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <Window.h>


#include <View.h>
#include <Bitmap.h>
#include "LJAboutMainView/LJAboutMainView.h"

#include <stdio.h>
#include "VersionInfo.h"



#ifndef _LJAboutWindow_

class LJAboutWindow : public BWindow
{
public:
	/* Constructors & Destructor*/
	LJAboutWindow ();
	~LJAboutWindow (void);

	/* Hooks */

	virtual bool QuitRequested(void);
//	virtual void MessageReceived(BMessage *message);
//	virtual void FrameMoved(BPoint origin);
//	virtual void FrameResized(float width, float height);
//	virtual void WindowActivated(bool active);
//	virtual void WorkspaceActivated(int32 workspace, bool active);
//	virtual void WorkspacesChanged(uint32 oldWorkspaces, uint32 newWorkspaces);
//	virtual void Minimize(bool minimize);
//	virtual void Zoom(BPoint origin, float width, float height);
//	virtual void Show(void);
//	virtual void Hide(void);
//	virtual void ScreenChanged(BRect frame, color_space mode);
//	virtual void MenusBeginning(void);
//	virtual void MenusEnded(void);
//	virtual void DispatchMessage(BMessage *message, BHandler *target);
//	virtual BHandler * ResolveSpecifier(BMessage *msg, int32 index,	BMessage *specifier, int32 form,const char *property);
//	virtual status_t GetSupportedSuites(BMessage *data);
//	virtual status_t Perform(perform_code d, void *arg);
	LJAboutMainView * MainView;

};

#define _LJAboutWindow_
#endif
