/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <Window.h>


#include <View.h>
#include <Bitmap.h>
#include <TabView.h>
#include "LJViewFriends/LJViewFriends.h"
#include "LJViewFriendsOf/LJViewFriendsOf.h"
#include "LJViewHistory/LJViewHistory.h"



#ifndef _LJAccount_

class LJAccount : public BWindow
{
public:
	/* Constructors & Destructor*/
	LJAccount ();
	~LJAccount (void);

	/* Hooks */

	virtual bool QuitRequested(void);
	virtual void MessageReceived(BMessage *message);
//	virtual void FrameMoved(BPoint origin);
//	virtual void FrameResized(float width, float height);
//	virtual void WindowActivated(bool active);
//	virtual void WorkspaceActivated(int32 workspace, bool active);
//	virtual void WorkspacesChanged(uint32 oldWorkspaces, uint32 newWorkspaces);
//	virtual void Minimize(bool minimize);
//	virtual void Zoom(BPoint origin, float width, float height);
//	virtual void Show(void);
//	virtual void Hide(void);
//	virtual void ScreenChanged(BRect frame, color_space mode);
//	virtual void MenusBeginning(void);
//	virtual void MenusEnded(void);
//	virtual void DispatchMessage(BMessage *message, BHandler *target);
//	virtual BHandler * ResolveSpecifier(BMessage *msg, int32 index,	BMessage *specifier, int32 form,const char *property);
//	virtual status_t GetSupportedSuites(BMessage *data);
//	virtual status_t Perform(perform_code d, void *arg);
	BView * MainView;
	BTabView * tabview1;
	LJViewFriends * viewfriends;
	LJViewFriendsOf * viewfriendof;
	LJViewHistory * viewHistory;
	void	FillList(void);
	void	CompareLists(void);
	void	CleanUp(void);
	bool 	accept_closing;

};

#define _LJAccount_
#endif
