/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <View.h>
#include <Bitmap.h>
#include <string>
#include <PopUpMenu.h>
#include <ScrollView.h>
#include <MenuField.h>
#include <ListView.h>
#include <StringView.h>



#ifndef _LJViewHistory_

class LJViewHistory : public BView
{
public:
	/* Constructors & Destructor*/
	                LJViewHistory ();
	                ~LJViewHistory(void);

	/* Hooks */

	virtual void    AttachedToWindow(void);
	virtual void    AllAttached(void);
	virtual void    MessageReceived(BMessage *message);

	BScrollView     *scrollview3;
	BListView       *history_list;
	BStringView     *stringview5;
	BStringView     *journalText;
    BPopUpMenu      *journalMenu;
    BMenuField      *journalField;

    std::string          usejournal; 

	bool _bxl_attached;


};

#define _LJViewHistory_
#endif
