/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <Application.h>
#include "LJApplication/LJApplication.h"

int
main()
{
	new LJApplication();
	be_app->Run();
	delete be_app;
	return 0;
};
