/*
	This file was generated by BeXL
	Copyright (c) 2000 Simon Huet
*/


#include <View.h>
#include <Bitmap.h>


#include <ScrollView.h>
#include <ListView.h>
#include <StringView.h>
#include <Button.h>
#include <Application.h>



#ifndef _LJViewFriendsOf_

class LJViewFriendsOf : public BView
{
public:
	/* Constructors & Destructor*/
	LJViewFriendsOf ();
	~LJViewFriendsOf (void);

	/* Hooks */

	virtual void AttachedToWindow(void);
	virtual void AllAttached(void);
//	virtual void DetachedFromWindow(void);
//	virtual void AllDetached(void);
//	virtual void FrameMoved(BPoint parentPoint);
//	virtual void FrameResized(float width, float height);
//	virtual void KeyDown(const char *bytes, int32 numByte);
//	virtual void KeyUp(const char *bytes, int32 numByte);
//	virtual void MessageReceived(BMessage *message);
//	virtual void MouseDown(BPoint point);
//	virtual void MouseMoved(BPoint point, uint32 transit, const BMessage *message);
//	virtual void MouseUp(BPoint point);
//	virtual void WindowActivated(bool active);
//	virtual status_t Archive(BMessage *data, bool deep = true);
//	virtual void ConstrainClippingRegion(BRegion *region);
//	virtual void GetClippingRegion(BRegion *region);
//	virtual void Draw(BRect updateRect);
//	virtual void DrawAfterChildren(BRect updateRect);
//	virtual void GetPreferredSize(float *width, float *height);
//	virtual void ResizeToPreferred(void);
//	virtual status_t GetSupportedSuites(BMessage *data);
//	virtual void MakeFocus(bool focus = true);
//	virtual status_t Perform(perform_code d, void *arg);
//	virtual void Pulse(void);
//	virtual BHandler * ResolveSpecifier(BMessage *msg, int32 index,	BMessage *specifier, int32 form,const char *property);
//	virtual void ScrollTo(BPoint where);
//	virtual void SetDrawingMode(drawing_mode mode);
//	virtual void SetPenSize(float size);
//	virtual void SetViewColor(rgb_color color);
//	virtual void SetHighColor(rgb_color color);
//	virtual void SetLowColor(rgb_color color);
//	virtual void SetFont(const BFont *font, uint32 mask = B_FONT_ALL);
//	virtual void SetFlags(uint32 flags);
//	virtual void SetResizingMode(uint32 mode);
//	virtual void Show(void);
//	virtual void Hide(void);
//	virtual void TargetedByScrollView(BScrollView *scroller);
	BScrollView * scrollview2;
	BListView * friends_list;
	BStringView * stringview4;
	BButton * button5;
	void		FillList(void);
	thread_id	fill_thread;
	bool		listfilled;
	bool _bxl_attached;


};

#define _LJViewFriendsOf_
#endif
